name: ALL VM's Shutdown on Weekends

on:
  schedule:
    - cron: "0 */8 * * 6,0"
  push:
    branches:
      - main

env:
  PROJECT_VAR: soleng-dev
  DRYRUN_VAR: false

jobs:
  shutdown_all_vms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2       

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: "soleng-dev" # Replace with your project ID
          service_account_key: ${{ secrets.SOLENG_DEV_CREDENTIALS_JSON }} # Replace with your secret containing the service account key
          export_default_credentials: true


      - name: Run Shell Script
        run: |
          echo "Running shell script..."
          chmod +x vm_shutdown_all.sh
          ./vm_shutdown_all.sh $PROJECT_VAR $DRYRUN_VAR

