name: VM's and SQL DB Shutdown without OWNER

on:
  schedule:
    - cron: "*/30 * * * 1-5"
  push:
    branches:
      - main

env:
  PROJECT_VAR: soleng-dev
  DRYRUN_VAR: false

jobs:
  shutdown_all_vms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2       

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: "soleng-dev" # Replace with your project ID
          service_account_key: ${{ secrets.SOLENG_DEV_CREDENTIALS_JSON }} # Replace with your secret containing the service account key
          export_default_credentials: true


      - name: Run Shell Script
        run: |
          echo "Running shell script..."
          chmod +x vm_n_sql_shutdown_no_owner.sh
          ./vm_n_sql_shutdown_no_owner.sh $PROJECT_VAR $DRYRUN_VAR

